


document.write(" <html>");
document.write("    <head>");
document.write("    <title>ViaCEP Webservice<\/title>");
document.write("    <meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\" \/>");
document.write("");
document.write("    <!-- Adicionando Javascript -->");
document.write("    <script type=\"text\/javascript\" >");
document.write("    ");
document.write("    function limpa_formulário_cep() {");
document.write("            \/\/Limpa valores do formulário de cep.");
document.write("            document.getElementById('rua').value=(\"\");");
document.write("            document.getElementById('bairro').value=(\"\");");
document.write("            document.getElementById('cidade').value=(\"\");");
document.write("            document.getElementById('uf').value=(\"\");");
document.write("            document.getElementById('ibge').value=(\"\");");
document.write("    }");
document.write("");
document.write("    function meu_callback(conteudo) {");
document.write("        if (!(\"erro\" in conteudo)) {");
document.write("            \/\/Atualiza os campos com os valores.");
document.write("            document.getElementById('rua').value=(conteudo.logradouro);");
document.write("            document.getElementById('bairro').value=(conteudo.bairro);");
document.write("            document.getElementById('cidade').value=(conteudo.localidade);");
document.write("            document.getElementById('uf').value=(conteudo.uf);");
document.write("            document.getElementById('ibge').value=(conteudo.ibge);");
document.write("        } \/\/end if.");
document.write("        else {");
document.write("            \/\/CEP não Encontrado.");
document.write("            limpa_formulário_cep();");
document.write("            alert(\"CEP não encontrado.\");");
document.write("        }");
document.write("    }");
document.write("        ");
document.write("    function pesquisacep(valor) {");
document.write("");
document.write("        \/\/Nova variável \"cep\" somente com dígitos.");
document.write("        var cep = valor.replace(\/\D\/g, '');");
document.write("");
document.write("        \/\/Verifica se campo cep possui valor informado.");
document.write("        if (cep != \"\") {");
document.write("");
document.write("            \/\/Expressão regular para validar o CEP.");
document.write("            var validacep = \/^[0-9]{8}$\/;");
document.write("");
document.write("            \/\/Valida o formato do CEP.");
document.write("            if(validacep.test(cep)) {");
document.write("");
document.write("                \/\/Preenche os campos com \"...\" enquanto consulta webservice.");
document.write("                document.getElementById('rua').value=\"...\";");
document.write("                document.getElementById('bairro').value=\"...\";");
document.write("                document.getElementById('cidade').value=\"...\";");
document.write("                document.getElementById('uf').value=\"...\";");
document.write("                document.getElementById('ibge').value=\"...\";");
document.write("");
document.write("                \/\/Cria um elemento javascript.");
document.write("                var script = document.createElement('script');");
document.write("");
document.write("                \/\/Sincroniza com o callback.");
document.write("                script.src = 'https:\/\/viacep.com.br\/ws\/'+ cep + '\/json\/?callback=meu_callback';");
document.write("");
document.write("                \/\/Insere script no documento e carrega o conteúdo.");
document.write("                document.body.appendChild(script);");
document.write("");
document.write("            } \/\/end if.");
document.write("            else {");
document.write("                \/\/cep é inválido.");
document.write("                limpa_formulário_cep();");
document.write("                alert(\"Formato de CEP inválido.\");");
document.write("            }");
document.write("        } \/\/end if.");
document.write("        else {");
document.write("            \/\/cep sem valor, limpa formulário.");
document.write("            limpa_formulário_cep();");
document.write("        }");
document.write("    };");
document.write("");
document.write("    <\/script>");
document.write("    <\/head>");
document.write("");
document.write("    <body>");
document.write("    <!-- Inicio do formulario -->");
document.write("      <form method=\"get\" action=\".\">");
document.write("        <label>Cep:");
document.write("        <input name=\"cep\" type=\"text\" id=\"cep\" value=\"\" size=\"10\" maxlength=\"9\"");
document.write("               onblur=\"pesquisacep(this.value);\" \/><\/label><br \/>");
document.write("        <label>Rua:");
document.write("        <input name=\"rua\" type=\"text\" id=\"rua\" size=\"60\" \/><\/label><br \/>");
document.write("        <label>Bairro:");
document.write("        <input name=\"bairro\" type=\"text\" id=\"bairro\" size=\"40\" \/><\/label><br \/>");
document.write("        <label>Cidade:");
document.write("        <input name=\"cidade\" type=\"text\" id=\"cidade\" size=\"40\" \/><\/label><br \/>");
document.write("        <label>Estado:");
document.write("        <input name=\"uf\" type=\"text\" id=\"uf\" size=\"2\" \/><\/label><br \/>");
document.write("        <label>IBGE:");
document.write("        <input name=\"ibge\" type=\"text\" id=\"ibge\" size=\"8\" \/><\/label><br \/>");
document.write("      <\/form>");
document.write("    <\/body>");
document.write("");
document.write("    <\/html>");
